sudo: required
language: elixir
elixir:
  - 1.11
opt_release:
  - 23.0

addons:
  postgres: "9.4"

services:
 - postgresql

script:
  - mix format --check-formatted --dry-run
  - mix credo --strict
  - mix sobelow --config
  - mix coveralls.json
after_success:
  - bash <(curl -s https:/codecov.io/bash)
